### PR TITLE
IA3-1239 k12 lang override

### PR DESCRIPTION
**Pull request by HuiguangChu**

### CODE REVIEW

**Comment by gmcatalin** [comment]
Is this a new PR for the same thing ?

**Comment by HuiguangChu** [comment]
> Is this a new PR for the same thing ?

yeap... it will apply the k12 override from localStorage we set from Grading

**Comment by jqiang** [comment]
@mpereiraesaa can you review this PR?

**Comment by jqiang** [comment]
@mpereiraesaa can you take a look too?

**Comment by HuiguangChu** [comment]
> What happens when this is loaded only in the player ? Without new grading ? I don't think switching there reloads the page, does it ? And if it doesn't, it should load override the resource for all languages at start.

I just kept the same logic as 'local', the language stored in the local storage.

But probably we have to put the k12 override in the localStorage from the admin as well.  not only from grading/itemBank.

**Comment by HuiguangChu** [comment]
a general question: 
hypothesis will always be used with player together or not? @jqiang

**Comment by gmcatalin** [comment]
> > What happens when this is loaded only in the player ? Without new grading ? I don't think switching there reloads the page, does it ? And if it doesn't, it should load override the resource for all languages at start.
> 
> I just kept the same logic as 'local', the language stored in the local storage.
> 
> But probably we have to put the k12 override in the localStorage from the admin as well. not only from grading/itemBank.

What i meant is you kept the same logic as for new grading, where the window is reloaded on language switch. In the others (old grading, student dashboard) it isn't. So by overriding only the current selected language, on language switch, the others will be loaded with the not overridden resources.

**Comment by jqiang** [comment]
hypothesis will always be used with player together or not? yes, and yes to @gmcatalin's comment, it will always be used with player but not necessarily the "submission feature" in new grading

**Pull request merged**
