### PR TITLE
TEII-4743: append start and end aria labels

### PR DESCRIPTION
**Pull request by SergiiVdovareize**
https://inspera.atlassian.net/browse/TEII-4743
https://inspera.atlassian.net/browse/TEII-4766

test-player pr - https://github.com/inspera/test-player/pull/3530

The problem is in `:before` and `:after` elements. They are added because of acccesibility reasons for screen reader. But their content splits the word

image_2023-04-06_10-17-39

The solutions is replace them with empty invisible aria-label elements that are visible for screen reader only.

html before the changes:

image_2023-04-06_10-09-00

html after the changes:

image_2023-04-06_10-10-59

As a positive side effect, since the captions are not css already, we can provide translatable text.
I tested it with screen reader and it worked well

### CODE REVIEW

**Review by B612nian — APPROVED** [review]
I have added a note so that Manisha introduces a new Use Case related to annotation+screen reader that we can use as regression testing: 
https://inspera.atlassian.net/wiki/spaces/TESTC/pages/4191584321/SPEC%3A+%28Fjord%29+Words+getting+split+over+two+lines?focusedCommentId=4196270131

**Comment by SergiiVdovareize** [comment]
@B612nian so can it be merged now?

**Comment by B612nian** [comment]
@SergiiVdovareize to honor the pre-merge testing, would it be possible to deploy it so:
Screenshot 2023-04-12 at 09 03 46
(using `0.0.38` as it is the one expected by the Player)

**Comment by SergiiVdovareize** [comment]
Somehow it does not work. feature branch build fails

**Pull request merged**
